### ISSUE TITLE
Zoom in/out animation

### ISSUE THREAD

**Issue by aatalyk** [korre/android-tv-epg#17]
Hi @korre, thanks for this great library! I would like to implement zoom in/out animation for EPGEvent cause some text cant be visible properly. My approach is to increase hours per pixel but when I increase it and redraw scroller stays behind at the old position. I tried to move it by startScrolling to the time of the event but it is not smooth.

**Comment by l-k22** [comment]
Hi I too wanted to add zoom functionality, did you manage to do it, if so could you share your solution please
