### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ravinakalkani** [korre/android-tv-epg#19]
if i use this library in my phone then timebar interval is too close to each other in vertical mode.
How to set padding to time interval. because my event data is obverlapping when time interval is too close.

Plz help me
![Screenshot 2019-04-15 at 12 08 17 PM](https://user-images.githubusercontent.com/11885604/56111947-310a0d00-5f77-11e9-8559-633a6eb77dca.png)

**Comment by Aravindraj93** [comment]
You just need to decrease the value of HOURS_IN_VIEWPORT_MILLIS in your code. To reduce the view point to one hour change the HOURS_IN_VIEWPORT_MILLIS = 60 * 60 * 1000;
