### ISSUE TITLE
library export

### ISSUE THREAD

**Issue by lazarvgd** [korre/android-tv-epg#6]
Hi I have question about this project. I am new with android and really don't know how to add this solution to my project, is it possible to import it as gradle dependency or as library to existing project? 

thanks

**Comment by korre** [comment]
Hi,

It's unfortunately not available as a gradle dependency but it's easy to add to your project still.

You just need the epg package from: java/se/kmdev/tvepg

Then you need a couple of resources from the res package but you'll be aware of that when adding the epg package. Good luck!

**Comment by lazarvgd** [comment]
One more question it is not related to adding the project, but to navigation.

I am trying to enable navigation through the epg content with remote and I need indicator of current marked item. Is that possible to achieve with canvas?

thanks and sorry for inconvenience

**Comment by korre** [comment]
@lazarvgd. Yes it is. In the touch listener you might save the current pressed item. Then in onDraw you just check if this variable is set and change the background properly when drawing that particular item.
