### ISSUE TITLE
How do we enable Keyboard controls (Left/Right/Up/Down) in EPG

### ISSUE THREAD

**Issue by Raghuram143403** [korre/android-tv-epg#9]
Hi Kristoffer Matsson,

Since am developing an application on android TV so we need to control from Keyboard as well as remote.

Can you please help me here .

Thanks in Advance.

**Comment by acavazos1982** [comment]
I would also like to do this, right now it only works with touchscreen. @Raghuram143403 did you ever patch the current code to get it to work? Did you find another solution or did you build your own? Thanks.

**Comment by shekharbhadange-tudip** [comment]
Any update on this? I am also working on Android TV and need to work with the remote.

**Comment by korre** [comment]
Hi,

I think thats possible by adding a focusable state to the program items in the EPG and then setting nextFocus properties if necessary. 

See: https://developer.android.com/training/keyboard-input/navigation.html
